# Generated by Django 5.0.14 on 2025-12-14 23:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=100)),
                ('motif_procedure', models.TextField(blank=True, null=True)),
                ('statut', models.CharField(default='En cours', max_length=100)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('initiateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Procedure',
                'verbose_name_plural': 'Procedures',
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('telephone_paiement', models.CharField(help_text='Numéro Mobile Money utilisé pour le paiement', max_length=15)),
                ('montant', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('motif', models.CharField(blank=True, max_length=100, null=True)),
                ('initie_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('REUSSI', 'Réussi'), ('ECHOUE', 'Échoué')], default='EN_ATTENTE', max_length=20)),
                ('reference_transaction', models.CharField(blank=True, max_length=255, null=True)),
                ('procedure', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paiement', to='procedures.procedure')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
            },
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('matricule', models.CharField(max_length=100)),
                ('nom', models.CharField(blank=True, max_length=100, null=True)),
                ('prenom', models.CharField(blank=True, max_length=100, null=True)),
                ('filiere', models.CharField(blank=True, max_length=100, null=True)),
                ('ecole', models.CharField(blank=True, max_length=100, null=True)),
                ('moyenne_generale', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('procedure', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='etudiant', to='procedures.procedure')),
            ],
            options={
                'verbose_name': 'Etudiant',
                'verbose_name_plural': 'Etudiants',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.FilePathField(blank=True, null=True)),
                ('valeur', models.FileField(blank=True, null=True, upload_to='')),
                ('conformite', models.BooleanField(default=False)),
                ('certification', models.BooleanField(default=False)),
                ('signature_directeur', models.BooleanField(default=False)),
                ('approbation_rectorat', models.BooleanField(default=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='procedures.procedure')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
            },
        ),
        migrations.CreateModel(
            name='ReponseProcedure',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=100)),
                ('contenu', models.TextField(blank=True, null=True)),
                ('genere_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('procedure_liee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='procedures.procedure')),
            ],
            options={
                'verbose_name': 'Response Procedure',
                'verbose_name_plural': 'Response Procedures',
            },
        ),
    ]
