# Generated by Django 5.0.14 on 2025-12-14 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procedures', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='url',
        ),
    ]
