# Generated by Django 5.0.14 on 2025-12-15 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedures', '0002_remove_document_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='response_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='valeur',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('REUSSI', 'Réussi'), ('ECHOUE', 'Échoué'), ('EXPIRE', 'Expiré')], default='EN_ATTENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE_VALIDATION', 'En attente de validation'), ('VALIDEE', 'Validée'), ('REJETEE', 'Rejetée')], default='EN_ATTENTE_VALIDATION', max_length=100),
        ),
    ]
